[workspace]
members = [
    "0-smoke-test",
    "1-prime-time",
    "2-means-to-an-end",
    "3-budget-chat",
    "7-line-reversal",
    "8-insecure-sockets-layer",
    "9-job-centre",
    "protohackers-utils",
]
